"""Add user_id to schema_definitions for ownership

Revision ID: 28c1370ff4b5
Revises: c454111df232
Create Date: 2025-11-03 18:28:03.347569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c1370ff4b5'
down_revision: Union[str, Sequence[str], None] = 'c454111df232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_definitions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_schema_definitions_user_id'), 'schema_definitions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'schema_definitions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schema_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_schema_definitions_user_id'), table_name='schema_definitions')
    op.drop_column('schema_definitions', 'user_id')
    # ### end Alembic commands ###
