"""add_user_management_system

Revision ID: 46d6eb456b90
Revises: 8b22df3346df
Create Date: 2025-11-02 15:20:42.725129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d6eb456b90'
down_revision: Union[str, Sequence[str], None] = '8b22df3346df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import hashlib
    import uuid
    from datetime import datetime
    
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Create default admin user (matthew.carnali@parasail.io with password Hqbiscuit51!)
    admin_id = uuid.uuid4()
    admin_password_hash = hashlib.sha256("Hqbiscuit51!".encode()).hexdigest()
    
    conn = op.get_bind()
    conn.execute(
        sa.text("""
            INSERT INTO users (id, email, password_hash, full_name, is_admin, is_active, created_at, updated_at)
            VALUES (:id, :email, :password_hash, :full_name, :is_admin, :is_active, :created_at, :updated_at)
        """),
        {
            "id": str(admin_id),
            "email": "matthew.carnali@parasail.io",
            "password_hash": admin_password_hash,
            "full_name": "Matthew Carnali",
            "is_admin": True,
            "is_active": True,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow(),
        }
    )
    
    # Create test user (test@test.com with password test1234)
    test_user_id = uuid.uuid4()
    test_password_hash = hashlib.sha256("test1234".encode()).hexdigest()
    
    conn.execute(
        sa.text("""
            INSERT INTO users (id, email, password_hash, full_name, is_admin, is_active, created_at, updated_at)
            VALUES (:id, :email, :password_hash, :full_name, :is_admin, :is_active, :created_at, :updated_at)
        """),
        {
            "id": str(test_user_id),
            "email": "test@test.com",
            "password_hash": test_password_hash,
            "full_name": "Test User",
            "is_admin": False,
            "is_active": True,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow(),
        }
    )
    
    # Add user_id column as nullable first
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=True))
    
    # Set all existing documents to belong to admin user
    conn.execute(
        sa.text("UPDATE documents SET user_id = :admin_id WHERE user_id IS NULL"),
        {"admin_id": str(admin_id)}
    )
    
    # Now make user_id NOT NULL
    op.alter_column('documents', 'user_id', nullable=False)
    
    # Add index and foreign key
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_column('documents', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
