"""Add timing fields to document_ocr_results

Revision ID: 549cf3fc013e
Revises: e8a2e8a2a4f9
Create Date: 2025-11-01 17:06:57.207694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549cf3fc013e'
down_revision: Union[str, Sequence[str], None] = 'e8a2e8a2a4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ocr_results', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('document_ocr_results', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('document_ocr_results', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_ocr_results', 'duration_ms')
    op.drop_column('document_ocr_results', 'completed_at')
    op.drop_column('document_ocr_results', 'started_at')
    # ### end Alembic commands ###
