"""Add trash folder support to folders

Revision ID: 8b22df3346df
Revises: dd7363bfe470
Create Date: 2025-11-01 23:06:03.379764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b22df3346df'
down_revision: Union[str, Sequence[str], None] = 'dd7363bfe470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('folders', sa.Column('is_trash', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'is_trash')
    op.drop_column('folders', 'is_system')
    # ### end Alembic commands ###
