"""Add trash folder support to folders

Revision ID: 8b22df3346df
Revises: dd7363bfe470
Create Date: 2025-11-01 23:06:03.379764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b22df3346df'
down_revision: Union[str, Sequence[str], None] = 'dd7363bfe470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first with default values
    op.add_column('folders', sa.Column('is_system', sa.Boolean(), nullable=True))
    op.add_column('folders', sa.Column('is_trash', sa.Boolean(), nullable=True))
    
    # Update all existing rows to have default values
    op.execute('UPDATE folders SET is_system = FALSE WHERE is_system IS NULL')
    op.execute('UPDATE folders SET is_trash = FALSE WHERE is_trash IS NULL')
    
    # Now make them NOT NULL
    op.alter_column('folders', 'is_system', nullable=False, server_default=sa.false())
    op.alter_column('folders', 'is_trash', nullable=False, server_default=sa.false())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'is_trash')
    op.drop_column('folders', 'is_system')
    # ### end Alembic commands ###
