"""Add user_id and is_home to folders

Revision ID: 9721a65b3ddf
Revises: 5a19fd107af7
Create Date: 2025-11-02 17:39:01.789204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9721a65b3ddf'
down_revision: Union[str, Sequence[str], None] = '5a19fd107af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('user_id', sa.UUID(), nullable=True))
    # Add is_home as nullable first
    op.add_column('folders', sa.Column('is_home', sa.Boolean(), nullable=True))
    # Set default values for existing folders
    op.execute("UPDATE folders SET is_home = false WHERE is_home IS NULL")
    # Now make it non-nullable
    op.alter_column('folders', 'is_home', nullable=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_column('folders', 'is_home')
    op.drop_column('folders', 'user_id')
    # ### end Alembic commands ###
