"""Add is_public to schemas

Revision ID: c454111df232
Revises: b2c3d4e5f6a7
Create Date: 2025-11-03 18:18:40.497530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c454111df232'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_definitions_user_id'), table_name='schema_definitions')
    op.drop_constraint(op.f('fk_schema_definitions_user_id'), 'schema_definitions', type_='foreignkey')
    op.drop_column('schema_definitions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_definitions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_schema_definitions_user_id'), 'schema_definitions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_schema_definitions_user_id'), 'schema_definitions', ['user_id'], unique=False)
    # ### end Alembic commands ###
